broken-link-checker:
  exclude-directories:
    - .git/
    - docs/build/
    - third-party-licences/
  skip-urls:
    # Intentional broken links
    - https://www.google.com/teapot
    - https://google.com/nope.html
